# site settings

title: algotyrnt
description: I’m Punjitha aka algotyrnt.
taglong: personal website and blog for tyrnt
tagshort: tyrnt's website
url: https://algotyrnt.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/algotyrnt/algotyrnt.github.io

# author settings

author:
  name: Punjitha Bandara
  email: punjitha@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: algotyrnt
  github: algotyrnt
  instagram: algotyrnt
  linkedin: punjitha
  stackoverflow: 0000000/username
  twitter: algotyrnt

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
